export const noteInputConstants = {
  SET_NEW_NOTE_TITLE: "SET_NEW_NOTE_TITLE",
  SET_NEW_NOTE_TEXT: "SET_NEW_NOTE_TEXT",
  SET_NOTE_PREVIEW_ID: "SET_NOTE_PREVIEW_ID",
  SET_SEARCH_TEXT: "SET_SEARCH_TEXT",
};

export const noteListConstants = {
  ADD_NEW_NOTE: "ADD_NEW_NOTE",
  FETCH_NOTES: "FETCH_NOTES",
  DELETE_NOTE: "DELETE_NOTE",
  IS_EDIT: "IS_EDIT",
  UPDATE_NOTE: "UPDATE_NOTE",
};
